In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
# ocekujem da vidim niz od 0 do 10

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]
# Ako zelimo vrednost odredjenog indexa npr. 8mo mesto

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# od prvog mesta do 5 ispisuje niz

In [7]:
arr[0:5]
# od prvog do petog mesta zto znaci bice niz od 0 do 4

array([0, 1, 2, 3, 4])

In [8]:
arr[0:5] = 100
# sve vreednosti u nizu od 1 do 4. mesta odnosno od 0 do 4 stavi na vrednost 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# :D tacno ....

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]
# ocekujem slice od 0 do 5 
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99
#svi elementi ovog niza su jednaki 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# !!! kada menjamo niz sa slice-om menjamo originalni niz ne pravimo novi

In [19]:
# Ako zelimo da menjamo kopiju a da sacuvamo pocetni niz moramo to explicitno da navdemo
arr_copy = arr.copy()

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[1]
# Indeksiranjem visedimenzione matrice oznacavamo red... ovde indexiranjem 1 videcemo drugi red matrice

array([20, 25, 30])

In [26]:
#ako zelimo vrednost odredjenog clana matrice ispisujemo
arr_2d[1][2]
# prvi indeks red drugi index kolona znaci 2. red i 3. kolona

30

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[:2,1:]
# ako zelimo matricu 2x2 gornji desni ugao
# trazili smo red od 1 do 2 bez treceg i potom isekli kolone od [1] to znaci druge kolone do kraja

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[2]
# poslednji red

array([35, 40, 45])

In [30]:
arr2d = np.zeros((10,10))

In [31]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
arr_length = arr2d.shape[1]

In [39]:
arr_length
# ima duzinu od 10

10

In [42]:
for i in range(arr_length):
    arr2d[i] = 1
# promenicemo sve nule u jedinice

In [41]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [44]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [45]:
arr2d[[6,4,2,7]]
# vraca redove koje naznacimo

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])