In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1,sort=False)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
#adding markers and keys to concat result
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.rand(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.rand(3,3),columns=['Y','Q','X'])

In [14]:
dframe1

X         Y         Z
0  0.949789  0.860953  0.669379
1  0.867957  0.810679  0.090040
2  0.627565  0.801618  0.039845
3  0.092838  0.327844  0.335370

In [15]:
dframe2

Y         Q         X
0  0.592163  0.902209  0.852283
1  0.150053  0.316209  0.913967
2  0.833266  0.666091  0.248712

In [16]:
pd.concat([dframe1,dframe2]) #pd.concat([dframe1,dframe2],sort=False) without warrning

C:\Users\nenad\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.949789  0.860953  0.669379
1       NaN  0.867957  0.810679  0.090040
2       NaN  0.627565  0.801618  0.039845
3       NaN  0.092838  0.327844  0.335370
0  0.902209  0.852283  0.592163       NaN
1  0.316209  0.913967  0.150053       NaN
2  0.666091  0.248712  0.833266       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True,sort=False)

X         Y         Z         Q
0  0.949789  0.860953  0.669379       NaN
1  0.867957  0.810679  0.090040       NaN
2  0.627565  0.801618  0.039845       NaN
3  0.092838  0.327844  0.335370       NaN
4  0.852283  0.592163       NaN  0.902209
5  0.913967  0.150053       NaN  0.316209
6  0.248712  0.833266       NaN  0.666091