In [1]:
import numpy as np

In [ ]:
# np kako bi smo ga lakse pozivali

In [3]:
my_list1=[1,2,3,4]

In [12]:
# Pravimo niz od liste

In [5]:
my_array1 = np.array(my_list1)

In [ ]:
# ispisivanje napravljenog niza

In [6]:
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]

In [ ]:
# drugi niz i spajanje 23 niza

In [8]:
my_lists = [my_list1, my_list2]

In [9]:
my_array2 = np.array(my_lists)

In [ ]:
# dvodimenziona matrica

In [10]:
my_array2


array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [13]:
#provera velicine matrice 2x4


In [14]:
my_array2.shape

(2, 4)

In [15]:
my_array2.dtype

dtype('int32')

In [ ]:
# Matrica 1x5 sacinjena od nula floating type

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype

dtype('float64')

In [20]:
# matrica keceva 5x5


In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(5)

array([2.48006950e-312, 2.48006957e-312, 2.48006959e-312, 2.48006971e-312,
       2.48006976e-312])

In [23]:
np.empty(5).dtype

dtype('float64')

In [24]:
# multidimenzionalna matrica identity matrix glavna dijagonala jedinice

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# cesto koristimo matricu 

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
# prvi broj pocetak, drugi broj je kraj niza treci broj je step(skok)

In [28]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [30]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])