In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)
# Nalazimo kvadratni koren svakog clana u nizu

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)
# exponencialna e na cllana matrice

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A
# pravimo random niz od 10 clanova

array([-0.11256148,  0.19326143, -1.24092461,  0.84965878, -0.95149708,
       -1.11682714,  0.6253076 ,  0.21091815, -0.41086886,  0.2352156 ])

In [6]:
B = np.random.rand(10)

In [7]:
B

array([0.62079343, 0.16484772, 0.8902027 , 0.25836356, 0.36134666,
       0.75254206, 0.94288178, 0.1328619 , 0.577062  , 0.49682475])

In [8]:
# Binary Functions
np.add(A,B)

array([ 0.50823195,  0.35810915, -0.3507219 ,  1.10802235, -0.59015042,
       -0.36428508,  1.56818938,  0.34378005,  0.16619313,  0.73204034])

In [9]:
np.maximum(A,B)
# naci ce maximum izmedjju dve matrice

array([0.62079343, 0.19326143, 0.8902027 , 0.84965878, 0.36134666,
       0.75254206, 0.94288178, 0.21091815, 0.577062  , 0.49682475])

In [10]:
np.minimum(A,B)
# nalazi minimum izmedju clanova dve matrice

array([-0.11256148,  0.16484772, -1.24092461,  0.25836356, -0.95149708,
       -1.11682714,  0.6253076 ,  0.1328619 , -0.41086886,  0.2352156 ])

In [11]:
website = 

SyntaxError: invalid syntax (<ipython-input-11-cab4a02b1016>, line 1)